### ISSUE TITLE
Restructure Tests

### ISSUE THREAD

**Issue by jensdietrich** [veracitylab/provenance-injector#4]
1. Separate testing capture from JSON serialisation. 
2. For serialisation tests, could mock activities and entities. 
3. Separate classes for entity creation and entity propagation.

**Comment by jensdietrich** [comment]
For serialization test, please compare trees instead of string.

**Comment by Matrixuniverses** [comment]
Completed in d9ecdfad32b865a9670bfa441ed5fcf72251f791
