### ISSUE TITLE
add support to prov-json

### ISSUE THREAD

**Issue by jensdietrich** [veracitylab/provenance-injector#5]
the format is described here: https://www.w3.org/Submission/prov-json/

code to change:  nz.ac.wgtn.veracity.provenance.injector.model.<Class>::toJSON -- since we would not use databinding anymore, we could swap gson to json.org (note: exclude XML class from shading as it has a CVE)

try to use https://www.w3.org/Submission/prov-json/schema for testing

**Comment by Matrixuniverses** [comment]
Done in 471096a7ac6079532bb9cdc76c856c4c61b0c3f4
